---
title: "Descriptive stat and table 1"
format:
  html
---

```{r, message=FALSE}
library(here)
library(tidyverse)
library(tinytex)
library(PupillometryR)
library(DT)
#library(lme4)
library(car)
library(knitr)
library(kableExtra)
#library(sf)
library(tigris)
knitr::opts_knit$set(root.dir = here())
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
theme_set(theme_bw(base_size = 12)) # Use black/white theme and increase font size for all ggplot figures
library(table1)
library(readr)
library(dplyr)
```

### Read data

```{r}
vaccine <- read_csv("vaccine.csv")
```


### Data cleaning made by Lin

```{r}
county_total <- c(
  Arizona = 15, 
  Arkansas = 75, 
  Connecticut = 8, 
  Illinois = 102, 
  Maine = 16, 
  Massachusetts = 14, 
  Minnesota = 87, 
  Missouri = 114, 
  Montana = 56, 
  New_York = 62, 
  North_Dakota = 53, 
  Pennsylvania = 67, 
  South_Dakota = 66, 
  Texas = 254, 
  Utah = 29, 
  Florida = 67, 
  Idaho = 44, 
  Iowa = 99, 
  Michigan = 83, 
  New_Jersey = 21, 
  North_Carolina = 100, 
  Oklahoma = 77, 
  Rhode_Island = 5, 
  Tennessee = 95, 
  Virginia = 95, 
  Wisconsin = 72, 
  California = 58, 
  Colorado = 64, 
  Ohio = 88, 
  Oregon = 36, 
  Vermont = 14, 
  Washington = 39
)

## clean dtaset
vaccine_dat <- vaccine %>% 
  
  # recode vaccination coverage rates with -1 as missing
  mutate(overall_recode = ifelse(overall == -1, NA, overall),
         mmr_recode = ifelse(mmr == -1, NA, mmr)) %>%   
  
  # recode missing or 2017 school year as 2017-2018 (as per dataset description)
  mutate(year_recode = case_when(
    year == "null" ~ "2017-18",
    year == "2017" ~ "2017-18",
    TRUE ~ year)) %>%
  
  # recode school type into public and private schools
  mutate(type_recode = case_when(
    type == "BOCES" | type == "Kindergarten" | type == "Public" ~ "Public",
    type == "Charter" | type == "Nonpublic" | type == "Private" ~ "Private",
    TRUE ~ type)) %>%
  
  # create state spending per pupil variable
  mutate(spend_person = round(statespending2016/schagepop2016, 0)) %>% 

  # clean county name
  mutate(county = case_when(
    county == "State Of Illinois" ~ NA_character_,
    county == "BLAINE" ~ "Blaine",
    county == "ADA" ~ "Ada",
    county == "#N/A" ~ NA_character_,
    county == "Oklahoma/Tulsa" ~ "Oklahoma",
    county == "Walwroth" ~ "Walworth",
    county == "adams" ~ "Adams",
    county == "Colorado BOCS" ~ "Denver",
    county == "New Hampshire" ~ NA_character_,
    TRUE ~ county))


```



### Descriptive statistics

```{r}
total_data <- vaccine_dat %>%
  filter(mmr_recode != -1 | overall_recode != -1) %>%  
  summarise(
    private_total = sum(type_recode == "Private", na.rm = TRUE),
    public_total = sum(type_recode == "Public", na.rm = TRUE),
    na_total = sum(is.na(type_recode) | type_recode == " ", na.rm = TRUE))
```

```{r}
##** modified 2025mar22 - new table 1 stratified by vaccination group**

generate_table <- function(data, filter_conditions) {
  data %>%
    filter(!!!filter_conditions) %>%
    group_by(state) %>%
    
    summarise(
      county_number = n_distinct(county, na.rm = TRUE),
      school_number = length(name),
      
      private_number = sum(type_recode == "Private", na.rm = TRUE),
      public_number = sum(type_recode == "Public", na.rm = TRUE),
      na_number = sum(is.na(type_recode) | type_recode == " ", na.rm = TRUE),
      
      private_percent = round(private_number / total_data$private_total * 100, 0),
      public_percent = round(public_number / total_data$public_total * 100, 0),
      na_percent = round(na_number / total_data$na_total * 100, 0),
      
      spending = unique(statespending2016),
      spend_person = unique(spend_person),
      
      mean_overall = round(mean(overall_recode, na.rm = TRUE), 2),
      sd_overall = round(sd(overall_recode, na.rm = TRUE), 2),
      median_overall = round(median(overall_recode, na.rm = TRUE), 2),
      iqr_overall = round(IQR(overall_recode, na.rm = TRUE), 2),
      
      mean_mmr = round(mean(mmr_recode, na.rm = TRUE), 2),
      sd_mmr = round(sd(mmr_recode, na.rm = TRUE), 2),
      median_mmr = round(median(mmr_recode, na.rm = TRUE), 2),
      iqr_mmr = round(IQR(mmr_recode, na.rm = TRUE), 2)
      
    ) %>%
    mutate(across(everything(), ~ replace(., is.na(.), " "))) %>%

    mutate(
      private = paste0(private_number, " (", private_percent, "%)"),
      public = paste0(public_number, " (", public_percent, "%)"),
      na = paste0(na_number, " (", na_percent, "%)"),
      mean_sd_overall = paste0(mean_overall, " (", sd_overall, ")"),
      median_iqr_overall = paste0(median_overall, " (", iqr_overall, ")"),
      mean_sd_mmr = paste0(mean_mmr, " (", sd_mmr, ")"),
      median_iqr_mmr = paste0(median_mmr, " (", iqr_mmr, ")"))
  }

filter_mmr <- list(quote(mmr_recode != -1 | overall_recode != -1), 
                   quote(mmr_recode != " "), 
                   quote(!state %in% c("California", "Colorado", "Ohio", 
                                       "Oregon", "Vermont", "Washington")))

filter_overall <- list(quote(mmr_recode != -1 | overall_recode != -1), 
                       quote(overall_recode != " "), 
                       quote(!state %in% c("California", "Colorado", "Ohio", 
                                           "Oregon", "Vermont", "Washington")))

filter_both <- list(quote(mmr_recode != -1 | overall_recode != -1), 
                    quote(mmr_recode != " "), 
                    quote(overall_recode != " "))

table_mmr <- generate_table(vaccine_dat, filter_mmr)
table_overall <- generate_table(vaccine_dat, filter_overall)
table_both <- generate_table(vaccine_dat, filter_both)

table_combine <- bind_rows(table_mmr, table_overall, table_both)
```

```{r}
# #table_combine <- table_combine %>%
#   mutate(county_total = c(
#   15, 75, 8, 102, 16, 14, 87, 114, 56, 62, 53, 67, 66, 254, 29, 67, 44,
#   99, 83, 21, 100, 77, 5, 95, 133, 72, 58, 64, 88, 36, 14, 39)) %>%
#   mutate(county_number = as.numeric(county_number),
#          county_percent = round(county_number / county_total * 100, 0)) %>%
#   mutate(county = paste0(county_number, " (", county_percent, "%)"))

```


### Table 1

```{r}
##** modified 2025mar22 - new table 1 stratified by vaccination group**

table_combine %>% 
  select(state, county_number, school_number, private, 
         public, na, spending, spend_person, 
         mean_sd_overall, median_iqr_overall, 
         mean_sd_mmr, median_iqr_mmr) %>% 
  
  mutate(across(everything(), ~ replace(., . == "  ( )" |
                                           . == "  ( - )" , " "))) %>% 
  
  kable(col.names = c("Group / State",
                      "Number of county report",
                      "Number of school report",
                      "Private <br> (N = 3367)", 
                      "Public <br> (N = 13078)", 
                      "Unknown <br> (N = 25861)", 
                      "Per <br> state", "Per <br> person", 
                      "Mean (SD)", "Median (IQR)",
                      "Mean (SD)", "Median (IQR)"),
        format = "html", escape = FALSE) %>% 
  
  group_rows("MMR (N = 15)", 1, nrow(table_mmr)) %>% 
  group_rows("Overall (N = 11)", 
             nrow(table_mmr) + 1, 
             nrow(table_mmr) + 
             nrow(table_overall)) %>% 
  group_rows("MMR + Overall (N = 6)", 
             nrow(table_mmr) + 
             nrow(table_overall) + 1, 
             nrow(table_combine)) %>% 
  
add_header_above(c(" " = 1, " " = 2, "School type" = 3, 
                     "State spending (in $1,000)" = 2,
                     "Overall Vaccination Rate" = 2, "MMR Vaccination Rate" = 2))
```


```{r}

##** jwl added 2025mar18 - summarize data completion for the different models **
##*
#summary(vaccine_dat$mmr_recode)
#summary(vaccine_dat$overall_recode)

## check for duplicate school names
#dups <- vaccine_dat %>%
#  group_by(state, county, city, name) %>%
#  mutate(count = n()) %>%
#  ungroup()

#table(dups$count, useNA="ifany")


### create summary table for MMR 

## summarise number of schools reporting
num_school_mmr <- vaccine_dat %>%
  filter(!is.na(mmr_recode)) %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n_distinct(name)) %>%
  ungroup() %>%
  # summary statistics
  summarise(number_states = n(),
            total_schools = sum(number_schools),
            median_schools = median(number_schools),
            min_schools = min(number_schools),
            max_schools = max(number_schools))

## summarise number of schools reporting MMR and overall vaccination rates
enroll_mmr <- vaccine_dat %>%
  filter(!is.na(mmr_recode)) %>%
  mutate(has_enrollment = if_else(!is.na(enroll),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            reported_enrollment = sum(has_enrollment),
            perc_reported_enrollment = round(reported_enrollment/number_schools*100,1)) %>%
  ungroup() %>%
 # recode reported_enrollment=0 as missing
  mutate(perc_reported_enrollment = na_if(perc_reported_enrollment, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_with_enrollment = length(which(reported_enrollment!=0)),
            perc_states_w_enrollment = round(states_with_enrollment/number_states*100,1),
            min_perc_enrollment = min(perc_reported_enrollment, na.rm = T),
            max_perc_enrollment = max(perc_reported_enrollment, na.rm = T)
            ) %>%
  select(-number_states)
           
## summarise school type 
type_mmr <- vaccine_dat %>%
  filter(!is.na(mmr_recode)) %>%
  mutate(has_type = if_else(!is.na(type),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            reported_type = sum(has_type),
            perc_reported_type = round(reported_type/number_schools*100,1)) %>%
  ungroup() %>%
 # recode reported_enrollment=0 as missing
  mutate(perc_reported_type = na_if(perc_reported_type, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_w_schooltype = length(which(reported_type!=0)),
            perc_states_w_schooltype = round(states_w_schooltype/number_states*100,1)) %>%
  select(-number_states)

# has county
county_mmr <- vaccine_dat %>%
  filter(!is.na(mmr_recode)) %>%
  mutate(has_county = if_else(!is.na(county),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            with_county = sum(has_county),
            perc_reported_county = round(with_county/number_schools*100,1)) %>%
  ungroup() %>%
 # recode reported_enrollment=0 as missing
  mutate(perc_reported_county = na_if(perc_reported_county, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_w_county = length(which(with_county!=0)),
            min_perc_county = min(perc_reported_county, na.rm = T),
            max_perc_county = max(perc_reported_county, na.rm = T)
  ) %>%
  select(-number_states)
      
## combine columns
mmr_data_tab <- cbind(num_school_mmr, enroll_mmr, type_mmr, county_mmr) %>%
  mutate(Group = "MMR")
  

### create summary table for overall vaccination

## summarise number of schools reporting
num_school_all <- vaccine_dat %>%
  filter(!is.na(overall_recode)) %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n_distinct(name)) %>%
  ungroup() %>%
  # summary statistics
  summarise(number_states = n(),
            total_schools = sum(number_schools),
            median_schools = median(number_schools),
            min_schools = min(number_schools),
            max_schools = max(number_schools))

## summarise number of schools reporting MMR and overall vaccination rates
enroll_all <- vaccine_dat %>%
  filter(!is.na(overall_recode)) %>%
  mutate(has_enrollment = if_else(!is.na(enroll),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            reported_enrollment = sum(has_enrollment),
            perc_reported_enrollment = round(reported_enrollment/number_schools*100,1)) %>%
  ungroup() %>%
  # recode reported_enrollment=0 as missing
  mutate(perc_reported_enrollment = na_if(perc_reported_enrollment, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_with_enrollment = length(which(reported_enrollment!=0)),
            perc_states_w_enrollment = round(states_with_enrollment/number_states*100,1),
            min_perc_enrollment = min(perc_reported_enrollment, na.rm = T),
            max_perc_enrollment = max(perc_reported_enrollment, na.rm = T)
  ) %>%
  select(-number_states)

       
## summarise school type 
type_all <- vaccine_dat %>%
  filter(!is.na(overall_recode)) %>%
  mutate(has_type = if_else(!is.na(type),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            reported_type = sum(has_type),
            perc_reported_type = round(reported_type/number_schools*100,1)) %>%
  ungroup() %>%
 # recode reported_enrollment=0 as missing
  mutate(perc_reported_type = na_if(perc_reported_type, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_w_schooltype = length(which(reported_type!=0)),
            perc_states_w_schooltype = round(states_w_schooltype/number_states*100,1)) %>%
  select(-number_states)
      
# has county
county_all <- vaccine_dat %>%
  filter(!is.na(overall_recode)) %>%
  mutate(has_county = if_else(!is.na(county),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            with_county = sum(has_county),
            perc_reported_county = round(with_county/number_schools*100,1)) %>%
  ungroup() %>%
 # recode reported_enrollment=0 as missing
  mutate(perc_reported_county = na_if(perc_reported_county, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_w_county = length(which(with_county!=0)),
            min_perc_county = min(perc_reported_county, na.rm = T),
            max_perc_county = max(perc_reported_county, na.rm = T)
            ) %>%
  select(-number_states)

# combine columns
overall_data_tab <- cbind(num_school_all, enroll_all, type_all, county_all) %>%
  mutate(Group = "Overall")
  
            

### create summary table for both MMR & overall

## summarise number of schools reporting
num_school_both <- vaccine_dat %>%
  filter(!is.na(overall_recode) & !is.na(mmr_recode)) %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n_distinct(name)) %>%
  ungroup() %>%
  # summary statistics
  summarise(number_states = n(),
            total_schools = sum(number_schools),
            median_schools = median(number_schools),
            min_schools = min(number_schools),
            max_schools = max(number_schools))

## summarise number of schools reporting MMR and overall vaccination rates
enroll_both <- vaccine_dat %>%
  filter(!is.na(overall_recode) & !is.na(mmr_recode)) %>%
  mutate(has_enrollment = if_else(!is.na(enroll),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            reported_enrollment = sum(has_enrollment),
            perc_reported_enrollment = round(reported_enrollment/number_schools*100,1)) %>%
  ungroup() %>%
  # recode reported_enrollment=0 as missing
  mutate(perc_reported_enrollment = na_if(perc_reported_enrollment, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_with_enrollment = length(which(reported_enrollment!=0)),
            perc_states_w_enrollment = round(states_with_enrollment/number_states*100,1),
            min_perc_enrollment = min(perc_reported_enrollment, na.rm = T),
            max_perc_enrollment = max(perc_reported_enrollment, na.rm = T)
  ) %>%
  select(-number_states)

       
## summarise school type 
type_both <- vaccine_dat %>%
  filter(!is.na(overall_recode) & !is.na(mmr_recode)) %>%
  mutate(has_type = if_else(!is.na(type),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            reported_type = sum(has_type),
            perc_reported_type = round(reported_type/number_schools*100,1)) %>%
  ungroup() %>%
 # recode reported_enrollment=0 as missing
  mutate(perc_reported_type = na_if(perc_reported_type, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_w_schooltype = length(which(reported_type!=0)),
            perc_states_w_schooltype = round(states_w_schooltype/number_states*100,1)) %>%
  select(-number_states)
      
county_both <- vaccine_dat %>%
  filter(!is.na(overall_recode) & !is.na(mmr_recode)) %>%
  mutate(has_county = if_else(!is.na(county),1,0)) %>%
  distinct() %>%
  # create count of schools by state
  group_by(state) %>%
  summarise(number_schools = n(),
            with_county = sum(has_county),
            perc_reported_county = round(with_county/number_schools*100,1)) %>%
  ungroup() %>%
 # recode reported_enrollment=0 as missing
  mutate(perc_reported_county = na_if(perc_reported_county, 0)) %>%
  # count of states with enrollment counts
  summarise(number_states = n_distinct(state),
            states_w_county = length(which(with_county!=0)),
            min_perc_county = min(perc_reported_county, na.rm = T),
            max_perc_county = max(perc_reported_county, na.rm = T)
            ) %>%
  select(-number_states)

## combine columns
both_data_tab <- cbind(num_school_both, enroll_both, type_both, county_both) %>%
  mutate(Group = "MMR & Overall")
  

## create final table
data_completion_tab <- rbind(overall_data_tab, mmr_data_tab, both_data_tab) %>%
    relocate(Group, .before = number_states) 

data_completion_tab %>%
  # make it pretty
    kable(col.names = c("Group",
                        "Number of states", 
                      "Total schools", 
                      "Median schools per state", 
                      "Min schools per state",
                      "Max schools per state", 
                      "# states with enrollment data",
                      "% states with enrollment data",
                      "Min % schools in state reporting enrollment",
                      "Max % schools in state reporting enrollment", 
                      "# states reporting school type",
                      "% states reporting school type",
                      "# states with county",
                      "Min % schools in state with county",
                      "Max % schools in state with county" 
                      ),
        format = "html", escape = FALSE) 


```